In [19]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
# reading tour dataframes
df1 = pd.read_csv(r'..\Tour data\AbuDhabiclean.csv')
df2 = pd.read_csv(r'..\Tour data\AlUlaclean.csv')
df3 = pd.read_csv(r'..\Tour data\Antalyaclean.csv')
df4 = pd.read_csv(r'..\Tour data\Beijingclean.csv')
df5 = pd.read_csv(r'..\Tour data\Berlinclean.csv')
df6 = pd.read_csv(r'..\Tour data\Buenos Airesclean.csv')
df7 = pd.read_csv(r'..\Tour data\Cairoclean.csv')
df8 = pd.read_csv(r'..\Tour data\Cape Townclean.csv')
df9 = pd.read_csv(r'..\Tour data\Chicagoclean.csv')
df10 = pd.read_csv(r'..\Tour data\Riyadhclean.csv')
df11 = pd.read_csv(r'..\Tour data\Athensclean.csv')
df12 = pd.read_csv(r'..\Tour data\Dohaclean.csv')
df13 = pd.read_csv(r'..\Tour data\Istanbulclean.csv')
df14 = pd.read_csv(r'..\Tour data\Jeddahclean.csv')
df15 = pd.read_csv(r'..\Tour data\Kuala Lumpurclean.csv')
df16 = pd.read_csv(r'..\Tour data\Londonclean.csv')
df17 = pd.read_csv(r'..\Tour data\Madridclean.csv')
df18 = pd.read_csv(r'..\Tour data\Marrakechclean.csv')
df19 = pd.read_csv(r'..\Tour data\Mumbaiclean.csv')
df20 = pd.read_csv(r'..\Tour data\Muscatclean.csv')
df21 = pd.read_csv(r'..\Tour data\NewYorkclean.csv')
df22 = pd.read_csv(r'..\Tour data\Orlandoclean.csv')
df23 = pd.read_csv(r'..\Tour data\Rio de Janeiroclean.csv')
df24 = pd.read_csv(r'..\Tour data\Parisclean.csv')
df25 = pd.read_csv(r'..\Tour data\Romeclean.csv')
df26 = pd.read_csv(r'..\Tour data\Singaporeclean.csv')
df27 = pd.read_csv(r'..\Tour data\Shanghaiclean.csv')
df28 = pd.read_csv(r'..\Tour data\Seoulclean.csv')
df29 = pd.read_csv(r'..\Tour data\Tokyoclean.csv')
df30 = pd.read_csv(r'..\Tour data\Amsterdamclean.csv')
df31 = pd.read_csv(r'..\Tour data\Barcelonaclean.csv')
df32 = pd.read_csv(r'..\Tour data\Hong Kongclean.csv')
df33 = pd.read_csv(r'..\Tour data\LAclean.csv')
df34 = pd.read_csv(r'..\Tour data\LVclean.csv')
df35 = pd.read_csv(r'..\Tour data\Mexico Cityclean.csv')
df36 = pd.read_csv(r'..\Tour data\Sydneyclean.csv')
df37 = pd.read_csv(r'..\Tour data\Torontoclean.csv')
df38 = pd.read_csv(r'..\Tour data\Viennaclean.csv')

In [21]:
# Concatenating DataFrames 
all_dfs = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df21, df22, df23, df24, df25, df26, df27, df28, df29, df30, df31, df32, df33, df34, df35, df36, df37, df38]

df = pd.concat(all_dfs)

In [22]:
# drop the Unnamed: 0 column
df.drop('Unnamed: 0', axis=1, inplace=True)

In [23]:
# to check the concatenating
df.head()

,Image,Tour Name,Tour Type,Tour Duration,Tour Price,Price Per,Cancellation,Tour By,City,Country,Link
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clear all filters,Abu Dhabi,United Arab Emirates,NaN
1,https://dynamic-media-cdn.tripadvisor.com/medi...,Abu Dhabi Full-Day Sightseeing Tour from Dubai,Bus Tours,6+ hours,$40.00,per adult,Free cancellation,By RAH Tourism,Abu Dhabi,United Arab Emirates,https://www.tripadvisor.com/Attraction_Review-...
2,https://dynamic-media-cdn.tripadvisor.com/medi...,"Evening Desert Safari With BBQ Dinner, Camel R...",Shore Excursions,6 hours,$83.00,per adult,Free cancellation,By Emirates Tours and Safaris,Abu Dhabi,United Arab Emirates,https://www.tripadvisor.com/Attraction_Review-...
3,NaN,NaN,Cold feet?,NaN,NaN,NaN,NaN,NaN,Abu Dhabi,United Arab Emirates,NaN
4,https://dynamic-media-cdn.tripadvisor.com/medi...,Dubai to Abu Dhabi Grand Mosque & Qasr Al Wata...,Bus Tours,8–9 hours,$109.00,per adult,Free cancellation,By OceanAir Travels,Abu Dhabi,United Arab Emirates,https://www.tripadvisor.com/Attraction_Review-...

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16974 entries, 0 to 263
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Image          15775 non-null  object
 1   Tour Name      15813 non-null  object
 2   Tour Type      13984 non-null  object
 3   Tour Duration  16336 non-null  object
 4   Tour Price     15852 non-null  object
 5   Price Per      15813 non-null  object
 6   Cancellation   13447 non-null  object
 7   Tour By        16160 non-null  object
 8   City           16974 non-null  object
 9   Country        16974 non-null  object
 10  Link           15645 non-null  object
dtypes: object(11)
memory usage: 1.6+ MB

In [25]:
# Store the clean dataset
df.to_csv('all_Tours.csv')