In [35]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
# loading the dataframe
messy_df = pd.read_csv('Athens.csv')

In [37]:
# take a look of the first 5 rows in the data
messy_df.head()

,cctrW,iPqaD,iPqaD href,FmrIP href,dugSS src,bUshh,cIVmB,WlYyy 2,iPqaD href 2,WlYyy 3,WlYyy 4,ySnDE,WlYyy 5,WlYyy 6,cctrW 2,ccVGl,WlYyy 7,ccVGl 2,WlYyy 8,dXxty
0,"Tours, activities and experiences bookable on ...",Clear all filters,https://www.tripadvisor.com/ClientLink?value=Q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Not sure? You can cancel this reservation up t...,By Visit Meteora Travel,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Full-Day Meteora Tour from Athens by Train,1.0,185,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,6+ hours,The tour starts from Larissis train station in...,Free cancellation,96% of travelers recommend this experience,This number is based on the percentage of all ...,from,$76.93,per adult,More info,NaN
2,Not sure? You can cancel this reservation up t...,By Olive Sea Travel,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Athens Full Day Private Tour,2.0,195,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,6+ hours,Athens is on your bucket list and this is the ...,Free cancellation,97% of travelers recommend this experience,This number is based on the percentage of all ...,from,$135.76,per adult,More info,NaN
3,Not sure? You can cancel this reservation up t...,By Warmpenguin,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Full Day Private Tour: Essential Athens Highli...,3.0,64,https://www.tripadvisor.com/Attraction_Review-...,Car Tours,8â€“9 hours,Private flexible tour combining the Highlights...,Free cancellation,98% of travelers recommend this experience,This number is based on the percentage of all ...,from,$228.54,per adult,More info,NaN
4,Not sure? You can cancel this reservation up t...,By Alternative Athens,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Athens Highlights: a Mythological Tour,4.0,403,https://www.tripadvisor.com/Attraction_Review-...,Walking Tours,4 hours,History & Myth meet in Athens! Discover the gr...,Free cancellation,97% of travelers recommend this experience,This number is based on the percentage of all ...,from,$75.80,per adult,More info,NaN

In [38]:
# check the datatype & non-null count
messy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cctrW         393 non-null    object
 1   iPqaD         400 non-null    object
 2   iPqaD href    381 non-null    object
 3   FmrIP href    390 non-null    object
 4   dugSS src     390 non-null    object
 5   bUshh         390 non-null    object
 6   cIVmB         390 non-null    float64
 7   WlYyy 2       383 non-null    object
 8   iPqaD href 2  387 non-null    object
 9   WlYyy 3       347 non-null    object
 10  WlYyy 4       403 non-null    object
 11  ySnDE         387 non-null    object
 12  WlYyy 5       381 non-null    object
 13  WlYyy 6       132 non-null    object
 14  cctrW 2       131 non-null    object
 15  ccVGl         390 non-null    object
 16  WlYyy 7       391 non-null    object
 17  ccVGl 2       390 non-null    object
 18  WlYyy 8       391 non-null    object
 19  dXxty         232 non-null    object
dtypes: float64(1), object(19)
memory usage: 65.4+ KB

In [39]:
# making a cop of the data to clean it
df = messy_df.copy()

In [40]:
# dropping the unnecessary columns
df.drop(['cctrW', 'iPqaD href', 'FmrIP href', 'dugSS src', 'cIVmB', 'WlYyy 2', 'ySnDE', 'WlYyy 6', 'cctrW 2', 'ccVGl', 'WlYyy 8', 'dXxty'], axis=1 , inplace=True)

In [41]:
# renaming the columns
df.rename(columns={'iPqaD':'Tour By', 'bUshh':'Tour Name', 'iPqaD href 2':'Link', 'WlYyy 3':'Tour Type', 'WlYyy 4':'Tour Duration', 'WlYyy 5':'Cancellation', 'WlYyy 7':'Tour Price', 'ccVGl 2':'Price Per'}, inplace=True)

In [42]:
# adding new columns
df['City'] = 'Athens'
df['Country'] = 'Greece'

In [43]:
# check the total duplicated rows
sum(df.duplicated())

12

In [44]:
# drop the duplicated rows
df.drop_duplicates()

,Tour By,Tour Name,Link,Tour Type,Tour Duration,Cancellation,Tour Price,Price Per,City,Country
0,Clear all filters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Athens,Greece
1,By Visit Meteora Travel,Full-Day Meteora Tour from Athens by Train,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,6+ hours,Free cancellation,$76.93,per adult,Athens,Greece
2,By Olive Sea Travel,Athens Full Day Private Tour,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,6+ hours,Free cancellation,$135.76,per adult,Athens,Greece
3,By Warmpenguin,Full Day Private Tour: Essential Athens Highli...,https://www.tripadvisor.com/Attraction_Review-...,Car Tours,8â€“9 hours,Free cancellation,$228.54,per adult,Athens,Greece
4,By Alternative Athens,Athens Highlights: a Mythological Tour,https://www.tripadvisor.com/Attraction_Review-...,Walking Tours,4 hours,Free cancellation,$75.80,per adult,Athens,Greece
...,...,...,...,...,...,...,...,...,...,...
413,By Eatwith Athens,Greek dinner on a luxury terrace rooftop with ...,https://www.tripadvisor.com/Attraction_Review-...,NaN,3 hours,Free cancellation,$82.97,per adult,Athens,Greece
414,By electricityrides,Electricityrides | e-bike rentals,https://www.tripadvisor.com/Attraction_Review-...,Rentals,2â€“168 hours,Free cancellation,$22.63,per adult,Athens,Greece
415,By Crispy Local,Athens Iconic Highlights Private Guided Tour W...,https://www.tripadvisor.com/Attraction_Review-...,Car Tours,2â€“6 hours,Free cancellation,$130.11,per adult,Athens,Greece
416,By GREECE TAXI,"Cape Sounio, Poseidon Temple (5 hours). Day or...",https://www.tripadvisor.com/Attraction_Review-...,NaN,5 hours,Free cancellation,$59.87,per adult,Athens,Greece
417,NaN,NaN,NaN,14,16,NaN,NaN,NaN,Athens,Greece

In [45]:
df.columns

Index(['Tour By', 'Tour Name', 'Link', 'Tour Type', 'Tour Duration',
       'Cancellation', 'Tour Price', 'Price Per', 'City', 'Country'],
      dtype='object')

In [46]:
# Reorfer the columns
df = df[['Tour Name', 'Tour Type', 'Tour Duration', 'Tour Price', 'Price Per', 'Cancellation','Tour By', 'City', 'Country', 'Link']]

In [47]:
#checking for total null values
df.isnull().sum()

Tour Name        28
Tour Type        71
Tour Duration    15
Tour Price       27
Price Per        28
Cancellation     37
Tour By          18
City              0
Country           0
Link             31
dtype: int64

In [48]:
# reset the index
df.reset_index(drop=True)

,Tour Name,Tour Type,Tour Duration,Tour Price,Price Per,Cancellation,Tour By,City,Country,Link
0,NaN,NaN,NaN,NaN,NaN,NaN,Clear all filters,Athens,Greece,NaN
1,Full-Day Meteora Tour from Athens by Train,Bus Tours,6+ hours,$76.93,per adult,Free cancellation,By Visit Meteora Travel,Athens,Greece,https://www.tripadvisor.com/Attraction_Review-...
2,Athens Full Day Private Tour,Bus Tours,6+ hours,$135.76,per adult,Free cancellation,By Olive Sea Travel,Athens,Greece,https://www.tripadvisor.com/Attraction_Review-...
3,Full Day Private Tour: Essential Athens Highli...,Car Tours,8â€“9 hours,$228.54,per adult,Free cancellation,By Warmpenguin,Athens,Greece,https://www.tripadvisor.com/Attraction_Review-...
4,Athens Highlights: a Mythological Tour,Walking Tours,4 hours,$75.80,per adult,Free cancellation,By Alternative Athens,Athens,Greece,https://www.tripadvisor.com/Attraction_Review-...
...,...,...,...,...,...,...,...,...,...,...
413,Greek dinner on a luxury terrace rooftop with ...,NaN,3 hours,$82.97,per adult,Free cancellation,By Eatwith Athens,Athens,Greece,https://www.tripadvisor.com/Attraction_Review-...
414,Electricityrides | e-bike rentals,Rentals,2â€“168 hours,$22.63,per adult,Free cancellation,By electricityrides,Athens,Greece,https://www.tripadvisor.com/Attraction_Review-...
415,Athens Iconic Highlights Private Guided Tour W...,Car Tours,2â€“6 hours,$130.11,per adult,Free cancellation,By Crispy Local,Athens,Greece,https://www.tripadvisor.com/Attraction_Review-...
416,"Cape Sounio, Poseidon Temple (5 hours). Day or...",NaN,5 hours,$59.87,per adult,Free cancellation,By GREECE TAXI,Athens,Greece,https://www.tripadvisor.com/Attraction_Review-...
417,NaN,14,16,NaN,NaN,NaN,NaN,Athens,Greece,NaN

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Tour Name      390 non-null    object
 1   Tour Type      347 non-null    object
 2   Tour Duration  403 non-null    object
 3   Tour Price     391 non-null    object
 4   Price Per      390 non-null    object
 5   Cancellation   381 non-null    object
 6   Tour By        400 non-null    object
 7   City           418 non-null    object
 8   Country        418 non-null    object
 9   Link           387 non-null    object
dtypes: object(10)
memory usage: 32.8+ KB

**For the Cleaning:**

- By - Rmove Clear all filters 
- type - Remove What are the best places for tours in Athens? 
- duration - some number only some with + sign
- price - Remove $ convert to float

In [50]:
# Store the clean dataset
df.to_csv('Athensclean.csv')