In [9]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
# loading the dataframe
messy_df = pd.read_csv('Kuala Lumpur.csv')

In [11]:
messy_df.columns

Index(['WlYyy', 'cctrW', 'iPqaD', 'iPqaD href', 'FmrIP href', 'dugSS src',
       'bUshh', 'cIVmB', 'iPqaD href 2', 'WlYyy 2', 'WlYyy 3', 'ySnDE',
       'WlYyy 4', 'ccVGl', 'WlYyy 6', 'ccVGl 2', 'WlYyy 7', 'dXxty'],
      dtype='object')

In [12]:
# take a look of the first 5 rows in the data
messy_df.head()

,WlYyy,cctrW,iPqaD,iPqaD href,FmrIP href,dugSS src,bUshh,cIVmB,iPqaD href 2,WlYyy 2,WlYyy 3,ySnDE,WlYyy 4,ccVGl,WlYyy 6,ccVGl 2,WlYyy 7,dXxty
0,"1,000+ places sorted by traveler favorites","Tours, activities and experiences bookable on ...",Clear all filters,https://www.tripadvisor.com/ClientLink?value=V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10,Not sure? You can cancel this reservation up t...,By Kuala Lumpur Tours,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Private Half-Day Kuala Lumpur City Tour with K...,1.0,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,3â€“4 hours,"Kuala Lumpur is the capital of Malaysia, and a...",Free cancellation,from,$38.47,per adult,More info,NaN
2,NaN,Not sure? You can cancel this reservation up t...,By Asni Global,NaN,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Putrajaya Tours with Perahu Dondang Sayang fro...,2.0,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,4 hours,Enjoy a venturing to the edges of Kuala Lumpur...,Free cancellation,from,$61.54,per adult,More info,Taking safety measures
3,161,Not sure? You can cancel this reservation up t...,By Menara Kuala Lumpur,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,KL Tower Observation Deck Admission Ticket,3.0,https://www.tripadvisor.com/Attraction_Review-...,Skyscrapers & Towers,1 hour,A visit to the KL Tower Observation Deck is a ...,Free cancellation,from,$19.11,per adult,More info,NaN
4,102,Not sure? You can cancel this reservation up t...,By Withlocals,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Discover the Best Local Food Tour by Night in ...,4.0,https://www.tripadvisor.com/Attraction_Review-...,Night Tours,2 hours,Enjoy the local food like all Malaysians do; c...,Free cancellation,from,$35.07,per adult,More info,NaN

In [13]:
# check the datatype & non-null count
messy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   WlYyy         209 non-null    object
 1   cctrW         232 non-null    object
 2   iPqaD         244 non-null    object
 3   iPqaD href    198 non-null    object
 4   FmrIP href    245 non-null    object
 5   dugSS src     242 non-null    object
 6   bUshh         245 non-null    object
 7   cIVmB         245 non-null    float64
 8   iPqaD href 2  236 non-null    object
 9   WlYyy 2       225 non-null    object
 10  WlYyy 3       255 non-null    object
 11  ySnDE         244 non-null    object
 12  WlYyy 4       233 non-null    object
 13  ccVGl         245 non-null    object
 14  WlYyy 6       246 non-null    object
 15  ccVGl 2       245 non-null    object
 16  WlYyy 7       246 non-null    object
 17  dXxty         135 non-null    object
dtypes: float64(1), object(17)
memory usage: 37.2+ KB

In [14]:
# making a cop of the data to clean it
df = messy_df.copy()

In [15]:
# dropping the unnecessary columns
df.drop(['WlYyy', 'cctrW','iPqaD href', 'FmrIP href', 'dugSS src', 'cIVmB', 'ySnDE', 'ccVGl','WlYyy 7', 'dXxty'], axis=1 , inplace=True)

In [16]:
# renaming the columns
df.rename(columns={'iPqaD':'Tour By', 'bUshh':'Tour Name', 'iPqaD href 2':'Link', 'WlYyy 2':'Tour Type', 'WlYyy 3':'Tour Duration', 'WlYyy 4':'Cancellation', 'WlYyy 6':'Tour Price', 'ccVGl 2':'Price Per'}, inplace=True)

In [17]:
# adding new columns
df['City'] = 'Kuala Lumpur'
df['Country'] = 'Malaysia'

In [18]:
# check the total duplicated rows
sum(df.duplicated())

12

In [19]:
# drop the duplicated rows
df.drop_duplicates()

,Tour By,Tour Name,Link,Tour Type,Tour Duration,Cancellation,Tour Price,Price Per,City,Country
0,Clear all filters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kuala Lumpur,Malaysia
1,By Kuala Lumpur Tours,Private Half-Day Kuala Lumpur City Tour with K...,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,3â€“4 hours,Free cancellation,$38.47,per adult,Kuala Lumpur,Malaysia
2,By Asni Global,Putrajaya Tours with Perahu Dondang Sayang fro...,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,4 hours,Free cancellation,$61.54,per adult,Kuala Lumpur,Malaysia
3,By Menara Kuala Lumpur,KL Tower Observation Deck Admission Ticket,https://www.tripadvisor.com/Attraction_Review-...,Skyscrapers & Towers,1 hour,Free cancellation,$19.11,per adult,Kuala Lumpur,Malaysia
4,By Withlocals,Discover the Best Local Food Tour by Night in ...,https://www.tripadvisor.com/Attraction_Review-...,Night Tours,2 hours,Free cancellation,$35.07,per adult,Kuala Lumpur,Malaysia
...,...,...,...,...,...,...,...,...,...,...
259,By Fun filled tours with KBK Tours & Transport...,Full Day Tour Tantalising Malacca,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,4â€“8 hours,NaN,$90.00,per adult,Kuala Lumpur,Malaysia
260,By Asni Tours & Travels,Ipoh Private Day Tour from Kuala Lumpur,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,10â€“11 hours,Free cancellation,$108.62,per adult,Kuala Lumpur,Malaysia
261,By Way to Kuala Lumpur,Genting Highlands Private Day Tour with Batu C...,https://www.tripadvisor.com/Attraction_Review-...,Cable Car Tours,6+ hours,Free cancellation,$139.00,per adult,Kuala Lumpur,Malaysia
262,By Asni Tours & Travels,Kuala Lumpur to Cherating One Way Private Tran...,https://www.tripadvisor.com/Attraction_Review-...,NaN,4 hours,Free cancellation,$108.00,per adult,Kuala Lumpur,Malaysia
263,NaN,NaN,NaN,1,11,13,NaN,NaN,Kuala Lumpur,Malaysia

In [20]:
df.columns

Index(['Tour By', 'Tour Name', 'Link', 'Tour Type', 'Tour Duration',
       'Cancellation', 'Tour Price', 'Price Per', 'City', 'Country'],
      dtype='object')

In [21]:
# Reorfer the columns
df = df[['Tour Name', 'Tour Type', 'Tour Duration', 'Tour Price', 'Price Per', 'Cancellation','Tour By', 'City', 'Country', 'Link']]

In [22]:
#checking for total null values
df.isnull().sum()

Tour Name        19
Tour Type        39
Tour Duration     9
Tour Price       18
Price Per        19
Cancellation     31
Tour By          20
City              0
Country           0
Link             28
dtype: int64

In [23]:
# reset the index
df.reset_index(drop=True)

,Tour Name,Tour Type,Tour Duration,Tour Price,Price Per,Cancellation,Tour By,City,Country,Link
0,NaN,NaN,NaN,NaN,NaN,NaN,Clear all filters,Kuala Lumpur,Malaysia,NaN
1,Private Half-Day Kuala Lumpur City Tour with K...,Bus Tours,3â€“4 hours,$38.47,per adult,Free cancellation,By Kuala Lumpur Tours,Kuala Lumpur,Malaysia,https://www.tripadvisor.com/Attraction_Review-...
2,Putrajaya Tours with Perahu Dondang Sayang fro...,Bus Tours,4 hours,$61.54,per adult,Free cancellation,By Asni Global,Kuala Lumpur,Malaysia,https://www.tripadvisor.com/Attraction_Review-...
3,KL Tower Observation Deck Admission Ticket,Skyscrapers & Towers,1 hour,$19.11,per adult,Free cancellation,By Menara Kuala Lumpur,Kuala Lumpur,Malaysia,https://www.tripadvisor.com/Attraction_Review-...
4,Discover the Best Local Food Tour by Night in ...,Night Tours,2 hours,$35.07,per adult,Free cancellation,By Withlocals,Kuala Lumpur,Malaysia,https://www.tripadvisor.com/Attraction_Review-...
...,...,...,...,...,...,...,...,...,...,...
259,Full Day Tour Tantalising Malacca,Bus Tours,4â€“8 hours,$90.00,per adult,NaN,By Fun filled tours with KBK Tours & Transport...,Kuala Lumpur,Malaysia,https://www.tripadvisor.com/Attraction_Review-...
260,Ipoh Private Day Tour from Kuala Lumpur,Bus Tours,10â€“11 hours,$108.62,per adult,Free cancellation,By Asni Tours & Travels,Kuala Lumpur,Malaysia,https://www.tripadvisor.com/Attraction_Review-...
261,Genting Highlands Private Day Tour with Batu C...,Cable Car Tours,6+ hours,$139.00,per adult,Free cancellation,By Way to Kuala Lumpur,Kuala Lumpur,Malaysia,https://www.tripadvisor.com/Attraction_Review-...
262,Kuala Lumpur to Cherating One Way Private Tran...,NaN,4 hours,$108.00,per adult,Free cancellation,By Asni Tours & Travels,Kuala Lumpur,Malaysia,https://www.tripadvisor.com/Attraction_Review-...
263,NaN,1,11,NaN,NaN,13,NaN,Kuala Lumpur,Malaysia,NaN

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Tour Name      245 non-null    object
 1   Tour Type      225 non-null    object
 2   Tour Duration  255 non-null    object
 3   Tour Price     246 non-null    object
 4   Price Per      245 non-null    object
 5   Cancellation   233 non-null    object
 6   Tour By        244 non-null    object
 7   City           264 non-null    object
 8   Country        264 non-null    object
 9   Link           236 non-null    object
dtypes: object(10)
memory usage: 20.8+ KB

**For the Cleaning:**
- by: REMOVE Clear all filters 
- type: REMOVE We focus on most happening history, food, attraction places and shopping mall or the most beautiful nature in Malaysia.& Q? & num
- duration: REMOVE Q? & num & + & H M D
- canel: REMOVE other
- price:$ --> float

In [25]:
# Store the clean dataset
df.to_csv('Kuala Lumpurclean.csv')