In [1]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# loading the dataframe
messy_df = pd.read_csv('Madrid.csv')

In [3]:
messy_df.columns

Index(['WlYyy', 'cctrW', 'iPqaD', 'iPqaD href', 'FmrIP href', 'dugSS src',
       'bUshh', 'cIVmB', 'iPqaD href 2', 'WlYyy 2', 'WlYyy 3', 'ySnDE',
       'WlYyy 4', 'WlYyy 5', 'cctrW 2', 'ccVGl', 'WlYyy 6', 'ccVGl 2',
       'WlYyy 7', 'dXxty'],
      dtype='object')

In [4]:
# take a look of the first 5 rows in the data
messy_df.head()

,WlYyy,cctrW,iPqaD,iPqaD href,FmrIP href,dugSS src,bUshh,cIVmB,iPqaD href 2,WlYyy 2,WlYyy 3,ySnDE,WlYyy 4,WlYyy 5,cctrW 2,ccVGl,WlYyy 6,ccVGl 2,WlYyy 7,dXxty
0,"1,000+ places sorted by traveler favorites","Tours, activities and experiences bookable on ...",Clear all filters,https://www.tripadvisor.com/ClientLink?value=e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,401,Not sure? You can cancel this reservation up t...,By Fun and Tickets Madrid,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Full Day Tour √Åvila and Segovia from Madrid wi...,1.0,https://www.tripadvisor.com/Attraction_Review-...,Full-day Tours,6+ hours,Only Tour to Avila and Segovia Rated 5 Star - ...,Free cancellation,96% of travelers recommend this experience,This number is based on the percentage of all ...,from,$87.11,per adult,More info,NaN
2,455,Not sure? You can cancel this reservation up t...,By Gourmet Madrid Tours,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Madrid Tapas and Wine Tasting Tour,2.0,https://www.tripadvisor.com/Attraction_Review-...,Wine Tours,3 hours,"In this all included tapas tour, discover Madr...",Free cancellation,98% of travelers recommend this experience,This number is based on the percentage of all ...,from,$90.51,per adult,More info,NaN
3,399,Not sure? You can cancel this reservation up t...,By Fun and Tickets Madrid,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Full-Day Toledo Tour with Cathedral from Madrid,3.0,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,6+ hours,Only Tour to Toledo from Madrid Rated 5 Star -...,Free cancellation,98% of travelers recommend this experience,This number is based on the percentage of all ...,from,$101.82,per adult,More info,NaN
4,75,Not sure? You can cancel this reservation up t...,By Torres Bermejas,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Flamenco Show & Special Menu at Torres Bermeja...,4.0,https://www.tripadvisor.com/Attraction_Review-...,Shows,1 hour,"Torres Bermejas, opened in 1960, is the most i...",Free cancellation,93% of travelers recommend this experience,This number is based on the percentage of all ...,from,$28.28,per adult,More info,NaN

In [5]:
# check the datatype & non-null count
messy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   WlYyy         452 non-null    object
 1   cctrW         499 non-null    object
 2   iPqaD         528 non-null    object
 3   iPqaD href    432 non-null    object
 4   FmrIP href    515 non-null    object
 5   dugSS src     515 non-null    object
 6   bUshh         515 non-null    object
 7   cIVmB         515 non-null    float64
 8   iPqaD href 2  511 non-null    object
 9   WlYyy 2       475 non-null    object
 10  WlYyy 3       534 non-null    object
 11  ySnDE         509 non-null    object
 12  WlYyy 4       500 non-null    object
 13  WlYyy 5       152 non-null    object
 14  cctrW 2       138 non-null    object
 15  ccVGl         515 non-null    object
 16  WlYyy 6       516 non-null    object
 17  ccVGl 2       515 non-null    object
 18  WlYyy 7       516 non-null    object
 19  dXxty         304 non-null    object
dtypes: float64(1), object(19)
memory usage: 86.4+ KB

In [6]:
# making a cop of the data to clean it
df = messy_df.copy()

In [7]:
# dropping the unnecessary columns
df.drop(['WlYyy', 'cctrW','iPqaD href', 'FmrIP href',  'cIVmB',  'ySnDE','WlYyy 5', 'cctrW 2', 'ccVGl','WlYyy 7', 'dXxty'], axis=1 , inplace=True)

In [8]:
# renaming the columns
df.rename(columns={'dugSS src':'Image','iPqaD':'Tour By', 'bUshh':'Tour Name', 'iPqaD href 2':'Link', 'WlYyy 2':'Tour Type', 'WlYyy 3':'Tour Duration', 'WlYyy 4':'Cancellation', 'WlYyy 6':'Tour Price', 'ccVGl 2':'Price Per'}, inplace=True)

In [9]:
# adding new columns
df['City'] = 'Madrid'
df['Country'] = 'Spain'

In [10]:
# check the total duplicated rows
sum(df.duplicated())

22

In [11]:
# drop the duplicated rows
df.drop_duplicates()

,Tour By,Image,Tour Name,Link,Tour Type,Tour Duration,Cancellation,Tour Price,Price Per,City,Country
0,Clear all filters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Madrid,Spain
1,By Fun and Tickets Madrid,https://dynamic-media-cdn.tripadvisor.com/medi...,Full Day Tour √Åvila and Segovia from Madrid wi...,https://www.tripadvisor.com/Attraction_Review-...,Full-day Tours,6+ hours,Free cancellation,$87.11,per adult,Madrid,Spain
2,By Gourmet Madrid Tours,https://dynamic-media-cdn.tripadvisor.com/medi...,Madrid Tapas and Wine Tasting Tour,https://www.tripadvisor.com/Attraction_Review-...,Wine Tours,3 hours,Free cancellation,$90.51,per adult,Madrid,Spain
3,By Fun and Tickets Madrid,https://dynamic-media-cdn.tripadvisor.com/medi...,Full-Day Toledo Tour with Cathedral from Madrid,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,6+ hours,Free cancellation,$101.82,per adult,Madrid,Spain
4,By Torres Bermejas,https://dynamic-media-cdn.tripadvisor.com/medi...,Flamenco Show & Special Menu at Torres Bermeja...,https://www.tripadvisor.com/Attraction_Review-...,Shows,1 hour,Free cancellation,$28.28,per adult,Madrid,Spain
...,...,...,...,...,...,...,...,...,...,...,...
547,By Raphael Tours Madrid,https://dynamic-media-cdn.tripadvisor.com/medi...,Skip The Line Madrid Prado Museum Private Tour...,https://www.tripadvisor.com/Attraction_Review-...,Private and Luxury,1‚Äì2 hours,Free cancellation,$141.42,per adult,Madrid,Spain
548,By Flytographer,https://dynamic-media-cdn.tripadvisor.com/medi...,Private Vacation Photography Session with Phot...,https://www.tripadvisor.com/Attraction_Review-...,NaN,1 hour,Free cancellation,$299.00,per group,Madrid,Spain
549,By Self-Guided Tours in Madrid,https://dynamic-media-cdn.tripadvisor.com/medi...,Private Self-Guided Madrid City Tour to Explor...,https://www.tripadvisor.com/Attraction_Review-...,Walking Tours,1‚Äì6 hours,NaN,$20.36,per group,Madrid,Spain
550,By Driveme Tours,https://dynamic-media-cdn.tripadvisor.com/medi...,Private Transfers: Madrid to or from Toledo,https://www.tripadvisor.com/Attraction_Review-...,NaN,45 minutes,Free cancellation,$248.90,per group,Madrid,Spain
551,NaN,NaN,NaN,NaN,1,19,21,NaN,NaN,Madrid,Spain

In [12]:
df.columns

Index(['Tour By', 'Image', 'Tour Name', 'Link', 'Tour Type', 'Tour Duration',
       'Cancellation', 'Tour Price', 'Price Per', 'City', 'Country'],
      dtype='object')

In [13]:
# Reorfer the columns
df = df[['Image','Tour Name', 'Tour Type', 'Tour Duration', 'Tour Price', 'Price Per', 'Cancellation','Tour By', 'City', 'Country', 'Link']]

In [14]:
#checking for total null values
df.isnull().sum()

Image            37
Tour Name        37
Tour Type        77
Tour Duration    18
Tour Price       36
Price Per        37
Cancellation     52
Tour By          24
City              0
Country           0
Link             41
dtype: int64

In [15]:
# reset the index
df.reset_index(drop=True)

,Image,Tour Name,Tour Type,Tour Duration,Tour Price,Price Per,Cancellation,Tour By,City,Country,Link
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clear all filters,Madrid,Spain,NaN
1,https://dynamic-media-cdn.tripadvisor.com/medi...,Full Day Tour √Åvila and Segovia from Madrid wi...,Full-day Tours,6+ hours,$87.11,per adult,Free cancellation,By Fun and Tickets Madrid,Madrid,Spain,https://www.tripadvisor.com/Attraction_Review-...
2,https://dynamic-media-cdn.tripadvisor.com/medi...,Madrid Tapas and Wine Tasting Tour,Wine Tours,3 hours,$90.51,per adult,Free cancellation,By Gourmet Madrid Tours,Madrid,Spain,https://www.tripadvisor.com/Attraction_Review-...
3,https://dynamic-media-cdn.tripadvisor.com/medi...,Full-Day Toledo Tour with Cathedral from Madrid,Bus Tours,6+ hours,$101.82,per adult,Free cancellation,By Fun and Tickets Madrid,Madrid,Spain,https://www.tripadvisor.com/Attraction_Review-...
4,https://dynamic-media-cdn.tripadvisor.com/medi...,Flamenco Show & Special Menu at Torres Bermeja...,Shows,1 hour,$28.28,per adult,Free cancellation,By Torres Bermejas,Madrid,Spain,https://www.tripadvisor.com/Attraction_Review-...
...,...,...,...,...,...,...,...,...,...,...,...
547,https://dynamic-media-cdn.tripadvisor.com/medi...,Skip The Line Madrid Prado Museum Private Tour...,Private and Luxury,1‚Äì2 hours,$141.42,per adult,Free cancellation,By Raphael Tours Madrid,Madrid,Spain,https://www.tripadvisor.com/Attraction_Review-...
548,https://dynamic-media-cdn.tripadvisor.com/medi...,Private Vacation Photography Session with Phot...,NaN,1 hour,$299.00,per group,Free cancellation,By Flytographer,Madrid,Spain,https://www.tripadvisor.com/Attraction_Review-...
549,https://dynamic-media-cdn.tripadvisor.com/medi...,Private Self-Guided Madrid City Tour to Explor...,Walking Tours,1‚Äì6 hours,$20.36,per group,NaN,By Self-Guided Tours in Madrid,Madrid,Spain,https://www.tripadvisor.com/Attraction_Review-...
550,https://dynamic-media-cdn.tripadvisor.com/medi...,Private Transfers: Madrid to or from Toledo,NaN,45 minutes,$248.90,per group,Free cancellation,By Driveme Tours,Madrid,Spain,https://www.tripadvisor.com/Attraction_Review-...
551,NaN,NaN,1,19,NaN,NaN,21,NaN,Madrid,Spain,NaN

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Image          515 non-null    object
 1   Tour Name      515 non-null    object
 2   Tour Type      475 non-null    object
 3   Tour Duration  534 non-null    object
 4   Tour Price     516 non-null    object
 5   Price Per      515 non-null    object
 6   Cancellation   500 non-null    object
 7   Tour By        528 non-null    object
 8   City           552 non-null    object
 9   Country        552 non-null    object
 10  Link           511 non-null    object
dtypes: object(11)
memory usage: 47.6+ KB

In [17]:
# Store the clean dataset
df.to_csv('Madridclean.csv')