In [9]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
# loading the dataframe
messy_df = pd.read_csv('Paris.csv')

In [11]:
messy_df.columns

Index(['WlYyy', 'cctrW', 'iPqaD', 'iPqaD href', 'FmrIP href', 'dugSS src',
       'bUshh', 'cIVmB', 'WlYyy 2', 'iPqaD href 2', 'WlYyy 3', 'WlYyy 4',
       'ySnDE', 'dXxty', 'WlYyy 5', 'ccVGl', 'WlYyy 6', 'ccVGl 2', 'WlYyy 7',
       'WlYyy 8', 'cctrW 2'],
      dtype='object')

In [12]:
# take a look of the first 5 rows in the data
messy_df.head()

,WlYyy,cctrW,iPqaD,iPqaD href,FmrIP href,dugSS src,bUshh,cIVmB,WlYyy 2,iPqaD href 2,...,WlYyy 4,ySnDE,dXxty,WlYyy 5,ccVGl,WlYyy 6,ccVGl 2,WlYyy 7,WlYyy 8,cctrW 2
0,"2,000+ places sorted by traveler favorites","Tours, activities and experiences bookable on ...",Clear all filters,https://www.tripadvisor.com/ClientLink?value=V...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BEST SELLER,Not sure? You can cancel this reservation up t...,By Bateaux Parisiens,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Bateaux Parisiens Seine River Gourmet Dinner &...,1.0,"1,024",https://www.tripadvisor.com/Attraction_Review-...,...,2–3 hours,Combine a glamorous dinner in Paris with sight...,Taking safety measures,Free cancellation,from,$122.19,per adult,More info,NaN,NaN
2,BEST SELLER,NaN,By Moulin Rouge,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Paris Moulin Rouge Cabaret Show with Champagne...,2.0,433,https://www.tripadvisor.com/Attraction_Review-...,...,2 hours,The Moulin Rouge is the number one show in Par...,Taking safety measures,NaN,from,$101.82,per adult,More info,NaN,NaN
3,BEST SELLER,Not sure? You can cancel this reservation up t...,By City Wonders,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Louvre Museum Skip-the-Line Guided Tour with V...,3.0,847,https://www.tripadvisor.com/Attraction_Review-...,...,3 hours,Take a small group or a private (depending on ...,NaN,Free cancellation,from,$63.36,per adult,More info,91% of travelers recommend this experience,This number is based on the percentage of all ...
4,NaN,Not sure? You can cancel this reservation up t...,By Blue Fox Travel - Blue Bike Tours,https://www.tripadvisor.com/AttractionProductR...,https://www.tripadvisor.com/AttractionProductR...,https://dynamic-media-cdn.tripadvisor.com/medi...,Normandy D-Day Small-Group Day Trip with Omaha...,4.0,431,https://www.tripadvisor.com/Attraction_Review-...,...,12–13 hours,Visit the most important D-Day sites in Norman...,NaN,Free cancellation,from,$237.59,per adult,More info,99% of travelers recommend this experience,This number is based on the percentage of all ...

In [13]:
# check the datatype & non-null count
messy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 716 entries, 0 to 715
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   WlYyy         192 non-null    object
 1   cctrW         594 non-null    object
 2   iPqaD         682 non-null    object
 3   iPqaD href    556 non-null    object
 4   FmrIP href    668 non-null    object
 5   dugSS src     666 non-null    object
 6   bUshh         668 non-null    object
 7   cIVmB         668 non-null    float64
 8   WlYyy 2       562 non-null    object
 9   iPqaD href 2  661 non-null    object
 10  WlYyy 3       621 non-null    object
 11  WlYyy 4       692 non-null    object
 12  ySnDE         666 non-null    object
 13  dXxty         403 non-null    object
 14  WlYyy 5       574 non-null    object
 15  ccVGl         668 non-null    object
 16  WlYyy 6       669 non-null    object
 17  ccVGl 2       668 non-null    object
 18  WlYyy 7       669 non-null    object
 19  WlYyy 8       167 non-null    object
 20  cctrW 2       166 non-null    object
dtypes: float64(1), object(20)
memory usage: 117.6+ KB

In [14]:
# making a cop of the data to clean it
df = messy_df.copy()

In [15]:
# dropping the unnecessary columns
df.drop(['WlYyy', 'cctrW','iPqaD href', 'FmrIP href', 'dugSS src', 'cIVmB', 'WlYyy 2', 'ySnDE', 'dXxty', 'WlYyy 7','WlYyy 8', 'cctrW 2'], axis=1 , inplace=True)

In [16]:
# renaming the columns
df.rename(columns={'iPqaD':'Tour By', 'bUshh':'Tour Name', 'iPqaD href 2':'Link', 'WlYyy 3':'Tour Type', 'WlYyy 4':'Tour Duration', 'WlYyy 5':'Cancellation', 'WlYyy 6':'Tour Price', 'ccVGl 2':'Price Per'}, inplace=True)

In [17]:
# adding new columns
df['City'] = 'Paris'
df['Country'] = 'Frence'

In [18]:
# check the total duplicated rows
sum(df.duplicated())

89

In [19]:
# drop the duplicated rows
df.drop_duplicates()

,Tour By,Tour Name,Link,Tour Type,Tour Duration,Cancellation,ccVGl,Tour Price,Price Per,City,Country
0,Clear all filters,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Paris,Frence
1,By Bateaux Parisiens,Bateaux Parisiens Seine River Gourmet Dinner &...,https://www.tripadvisor.com/Attraction_Review-...,Sunset Cruises,2–3 hours,Free cancellation,from,$122.19,per adult,Paris,Frence
2,By Moulin Rouge,Paris Moulin Rouge Cabaret Show with Champagne...,https://www.tripadvisor.com/Attraction_Review-...,Dinner and Show,2 hours,NaN,from,$101.82,per adult,Paris,Frence
3,By City Wonders,Louvre Museum Skip-the-Line Guided Tour with V...,https://www.tripadvisor.com/Attraction_Review-...,Private and Luxury,3 hours,Free cancellation,from,$63.36,per adult,Paris,Frence
4,By Blue Fox Travel - Blue Bike Tours,Normandy D-Day Small-Group Day Trip with Omaha...,https://www.tripadvisor.com/Attraction_Review-...,Bus Tours,12–13 hours,Free cancellation,from,$237.59,per adult,Paris,Frence
...,...,...,...,...,...,...,...,...,...,...,...
711,By VoiceMap Paris,Le Marais: Secret Stories & Invisible Details ...,https://www.tripadvisor.com/Attraction_Review-...,City Tours,40 minutes,NaN,from,$6.90,per adult,Paris,Frence
712,By SOROOMANTIC,Paris hotel Lovebox,https://www.tripadvisor.com/Attraction_Review-...,NaN,1 hour,Free cancellation,from,$73.54,per adult,Paris,Frence
713,By DAY TRIPS FROM PARIS (FRANCE) - CITY TOURS,LOIRE VALLEY: Private day-trip to visit Chambo...,https://www.tripadvisor.com/Attraction_Review-...,Rail Tours,6+ hours,Free cancellation,from,$650.53,per adult,Paris,Frence
714,By Bateaux Mouches,Bateaux Mouches Lunch Christmas Cruise,https://www.tripadvisor.com/Attraction_Review-...,Lunch Cruises,2–3 hours,NaN,from,$103.86,per adult,Paris,Frence
715,NaN,NaN,NaN,26,28,NaN,NaN,NaN,NaN,Paris,Frence

In [20]:
df.columns

Index(['Tour By', 'Tour Name', 'Link', 'Tour Type', 'Tour Duration',
       'Cancellation', 'ccVGl', 'Tour Price', 'Price Per', 'City', 'Country'],
      dtype='object')

In [21]:
# Reorfer the columns
df = df[['Tour Name', 'Tour Type', 'Tour Duration', 'Tour Price', 'Price Per', 'Cancellation','Tour By', 'City', 'Country', 'Link']]

In [22]:
#checking for total null values
df.isnull().sum()

Tour Name         48
Tour Type         95
Tour Duration     24
Tour Price        47
Price Per         48
Cancellation     142
Tour By           34
City               0
Country            0
Link              55
dtype: int64

In [23]:
# reset the index
df.reset_index(drop=True)

,Tour Name,Tour Type,Tour Duration,Tour Price,Price Per,Cancellation,Tour By,City,Country,Link
0,NaN,NaN,NaN,NaN,NaN,NaN,Clear all filters,Paris,Frence,NaN
1,Bateaux Parisiens Seine River Gourmet Dinner &...,Sunset Cruises,2–3 hours,$122.19,per adult,Free cancellation,By Bateaux Parisiens,Paris,Frence,https://www.tripadvisor.com/Attraction_Review-...
2,Paris Moulin Rouge Cabaret Show with Champagne...,Dinner and Show,2 hours,$101.82,per adult,NaN,By Moulin Rouge,Paris,Frence,https://www.tripadvisor.com/Attraction_Review-...
3,Louvre Museum Skip-the-Line Guided Tour with V...,Private and Luxury,3 hours,$63.36,per adult,Free cancellation,By City Wonders,Paris,Frence,https://www.tripadvisor.com/Attraction_Review-...
4,Normandy D-Day Small-Group Day Trip with Omaha...,Bus Tours,12–13 hours,$237.59,per adult,Free cancellation,By Blue Fox Travel - Blue Bike Tours,Paris,Frence,https://www.tripadvisor.com/Attraction_Review-...
...,...,...,...,...,...,...,...,...,...,...
711,Le Marais: Secret Stories & Invisible Details ...,City Tours,40 minutes,$6.90,per adult,NaN,By VoiceMap Paris,Paris,Frence,https://www.tripadvisor.com/Attraction_Review-...
712,Paris hotel Lovebox,NaN,1 hour,$73.54,per adult,Free cancellation,By SOROOMANTIC,Paris,Frence,https://www.tripadvisor.com/Attraction_Review-...
713,LOIRE VALLEY: Private day-trip to visit Chambo...,Rail Tours,6+ hours,$650.53,per adult,Free cancellation,By DAY TRIPS FROM PARIS (FRANCE) - CITY TOURS,Paris,Frence,https://www.tripadvisor.com/Attraction_Review-...
714,Bateaux Mouches Lunch Christmas Cruise,Lunch Cruises,2–3 hours,$103.86,per adult,NaN,By Bateaux Mouches,Paris,Frence,https://www.tripadvisor.com/Attraction_Review-...
715,NaN,26,28,NaN,NaN,NaN,NaN,Paris,Frence,NaN

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 716 entries, 0 to 715
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Tour Name      668 non-null    object
 1   Tour Type      621 non-null    object
 2   Tour Duration  692 non-null    object
 3   Tour Price     669 non-null    object
 4   Price Per      668 non-null    object
 5   Cancellation   574 non-null    object
 6   Tour By        682 non-null    object
 7   City           716 non-null    object
 8   Country        716 non-null    object
 9   Link           661 non-null    object
dtypes: object(10)
memory usage: 56.1+ KB

**For the Cleaning:**
- by: REMOVE Clear all filters
- type: REMOVE num
- duration: REMOVE num 
- canel: REMOVE other
- price:$ --> float

In [25]:
# Store the clean dataset
df.to_csv('Parisclean.csv')