In [9]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
# loading the dataframe
messy_df = pd.read_csv('Cape Town.csv')

In [11]:
# take a look of the first 5 rows in the data
messy_df.head()

,WlYyy,FmrIP href,dugSS src,bUshh,cIVmB,iPqaD href 2,WlYyy 2,WlYyy 3,iPqaD href 3,dugSS src 2,WlYyy 4,iPqaD,iPqaD href 5,WlYyy 5,dkvhj,WlYyy 6
0,"1,000+ places sorted by traveler favorites",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"17,004",https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,Table Mountain Aerial Cableway,1.0,https://www.tripadvisor.com/Attraction_Review-...,Trams,Open now,https://www.tripadvisor.com/Profile/SietseW9,https://dynamic-media-cdn.tripadvisor.com/medi...,By,SietseW9,https://www.tripadvisor.com/ShowUserReviews-g3...,"A must do in Cape Town, a quick fun ride up th...",cable car,with super friendly staff.
2,"14,217",https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,Victoria & Alfred Waterfront,2.0,https://www.tripadvisor.com/Attraction_Review-...,Marinas • Piers & Boardwalks,Open now,https://www.tripadvisor.com/Profile/belindat691,https://dynamic-media-cdn.tripadvisor.com/medi...,By,belindat691,https://www.tripadvisor.com/ShowUserReviews-g3...,A,shopping mall,with a good variety of shops to browse and buy...
3,"4,313",https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,Lion's Head,3.0,https://www.tripadvisor.com/Attraction_Review-...,Mountains,NaN,https://www.tripadvisor.com/Profile/wwkudu,https://dynamic-media-cdn.tripadvisor.com/medi...,By,wwkudu,https://www.tripadvisor.com/ShowUserReviews-g3...,It's a popular walk - start early to avoid the...,full moon,sunsets.
4,"8,998",https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,Cape Point Nature Reserve,4.0,https://www.tripadvisor.com/Attraction_Review-...,Nature & Wildlife Areas,NaN,https://www.tripadvisor.com/Profile/Kypreos,https://dynamic-media-cdn.tripadvisor.com/medi...,By,Kypreos,https://www.tripadvisor.com/ShowUserReviews-g3...,Nature Reserve is amazing the scenery the sea ...,Cape Point,NaN

In [12]:
# check the datatype & non-null count
messy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   WlYyy         254 non-null    object
 1   FmrIP href    245 non-null    object
 2   dugSS src     234 non-null    object
 3   bUshh         245 non-null    object
 4   cIVmB         245 non-null    float64
 5   iPqaD href 2  243 non-null    object
 6   WlYyy 2       254 non-null    object
 7   WlYyy 3       116 non-null    object
 8   iPqaD href 3  105 non-null    object
 9   dugSS src 2   105 non-null    object
 10  WlYyy 4       113 non-null    object
 11  iPqaD         105 non-null    object
 12  iPqaD href 5  105 non-null    object
 13  WlYyy 5       105 non-null    object
 14  dkvhj         105 non-null    object
 15  WlYyy 6       90 non-null     object
dtypes: float64(1), object(15)
memory usage: 32.1+ KB

In [13]:
# making a cop of the data to clean it
df = messy_df.copy()

In [14]:
# dropping the unnecessary columns
df.drop(['WlYyy', 'FmrIP href', 'dugSS src', 'cIVmB', 'iPqaD href 2','WlYyy 3', 'iPqaD href 3', 'dugSS src 2', 'WlYyy 4', 'iPqaD','iPqaD href 5', 'WlYyy 5', 'dkvhj', 'WlYyy 6'], axis=1 , inplace=True)

In [15]:
# renaming the columns
df.rename(columns={ 'bUshh':'Attraction Name', 'WlYyy 2':'Attraction Type'}, inplace=True)

In [16]:
# adding new columns
df['City'] = 'Cape Town'
df['Country'] = 'South Africa'

In [17]:
# check the total duplicated rows
sum(df.duplicated())

13

In [18]:
# drop the duplicated rows
df.drop_duplicates()

,Attraction Name,Attraction Type,City,Country
0,NaN,NaN,Cape Town,South Africa
1,Table Mountain Aerial Cableway,Trams,Cape Town,South Africa
2,Victoria & Alfred Waterfront,Marinas • Piers & Boardwalks,Cape Town,South Africa
3,Lion's Head,Mountains,Cape Town,South Africa
4,Cape Point Nature Reserve,Nature & Wildlife Areas,Cape Town,South Africa
...,...,...,...,...
250,4 Cape Town Day Tours,City Tours • Private Tours,Cape Town,South Africa
251,Jap Shuttles and Tours,Multi-day Tours • Distillery Tours,Cape Town,South Africa
252,Kirfara,Bike Tours • Walking Tours,Cape Town,South Africa
253,Icarus Tandem Paragliding Cape Town,Parasailing & Paragliding,Cape Town,South Africa
254,Jenman African Safaris,Multi-day Tours • Private Tours,Cape Town,South Africa

In [19]:
df.columns

Index(['Attraction Name', 'Attraction Type', 'City', 'Country'], dtype='object')

In [20]:
#checking for total null values
df.isnull().sum()

Attraction Name    11
Attraction Type     2
City                0
Country             0
dtype: int64

In [21]:
messy_df['WlYyy 2'].value_counts()

Art Galleries                                                  16
Speciality Museums                                             14
1                                                               9
Points of Interest & Landmarks                                  8
Nature & Wildlife Areas                                         7
                                                               ..
Points of Interest & Landmarks • Bridges                        1
Historic Sites • Historic Walking Areas                         1
Points of Interest & Landmarks • Observation Decks & Towers     1
Points of Interest & Landmarks • Universities & Schools         1
Multi-day Tours • Private Tours                                 1
Name: WlYyy 2, Length: 123, dtype: int64

In [22]:
# reset the index
df.reset_index(drop=True)

,Attraction Name,Attraction Type,City,Country
0,NaN,NaN,Cape Town,South Africa
1,Table Mountain Aerial Cableway,Trams,Cape Town,South Africa
2,Victoria & Alfred Waterfront,Marinas • Piers & Boardwalks,Cape Town,South Africa
3,Lion's Head,Mountains,Cape Town,South Africa
4,Cape Point Nature Reserve,Nature & Wildlife Areas,Cape Town,South Africa
...,...,...,...,...
251,Jap Shuttles and Tours,Multi-day Tours • Distillery Tours,Cape Town,South Africa
252,Kirfara,Bike Tours • Walking Tours,Cape Town,South Africa
253,Icarus Tandem Paragliding Cape Town,Parasailing & Paragliding,Cape Town,South Africa
254,Jenman African Safaris,Multi-day Tours • Private Tours,Cape Town,South Africa
255,NaN,1,Cape Town,South Africa

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Attraction Name  245 non-null    object
 1   Attraction Type  254 non-null    object
 2   City             256 non-null    object
 3   Country          256 non-null    object
dtypes: object(4)
memory usage: 8.1+ KB

In [24]:
# Store the clean dataset
df.to_csv('Cape Townclean.csv')