In [5]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
# loading the dataframe
messy_df = pd.read_csv('Marrakech.csv')

In [7]:
# take a look of the first 5 rows in the data
messy_df.head()

,WlYyy,FmrIP href,dugSS src,bUshh,cIVmB,iPqaD href 2,WlYyy 2,iPqaD href 3,dugSS src 2,WlYyy 3,iPqaD,iPqaD href 5,WlYyy 4,dkvhj,WlYyy 5,WlYyy 6
0,"3,000+ places sorted by traveler favorites",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"49,956",https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,Jardin Majorelle,1.0,https://www.tripadvisor.com/Attraction_Review-...,Gardens,https://www.tripadvisor.com/Profile/Mattel89,https://dynamic-media-cdn.tripadvisor.com/medi...,By,Mattel89,https://www.tripadvisor.com/ShowUserReviews-g2...,"Definitely “must see” in Marrakech,",beautiful garden,", lots of birds, amazing plants, palms, cactus...",NaN
2,"13,288",https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,Palácio da Bahia,2.0,https://www.tripadvisor.com/Attraction_Review-...,Historic Sites • Architectural Buildings,https://www.tripadvisor.com/Profile/fabfrench,https://dynamic-media-cdn.tripadvisor.com/medi...,By,fabfrench,https://www.tripadvisor.com/ShowUserReviews-g2...,The,Bahia Palace,is stunning and it is the perfect example of t...,Open now
3,716,https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,Anima André Heller Garden,3.0,https://www.tripadvisor.com/Attraction_Review-...,Gardens,https://www.tripadvisor.com/Profile/Jasonernesto,https://dynamic-media-cdn.tripadvisor.com/medi...,By,Jasonernesto,https://www.tripadvisor.com/ShowUserReviews-g2...,Spent a,few hours,here a few days ago and thoroughly enjoyed it.,Open now
4,"2,968",https://www.tripadvisor.com/Attraction_Review-...,https://dynamic-media-cdn.tripadvisor.com/medi...,Le Jardin Secret,4.0,https://www.tripadvisor.com/Attraction_Review-...,Gardens,https://www.tripadvisor.com/Profile/juliabG9395ZP,https://dynamic-media-cdn.tripadvisor.com/medi...,By,juliabG9395ZP,https://www.tripadvisor.com/ShowUserReviews-g2...,We visited,the secret garden,for the first time and were amazed by the peac...,Open now

In [8]:
# check the datatype & non-null count
messy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   WlYyy         257 non-null    object
 1   FmrIP href    246 non-null    object
 2   dugSS src     240 non-null    object
 3   bUshh         246 non-null    object
 4   cIVmB         246 non-null    float64
 5   iPqaD href 2  246 non-null    object
 6   WlYyy 2       256 non-null    object
 7   iPqaD href 3  106 non-null    object
 8   dugSS src 2   106 non-null    object
 9   WlYyy 3       115 non-null    object
 10  iPqaD         106 non-null    object
 11  iPqaD href 5  106 non-null    object
 12  WlYyy 4       112 non-null    object
 13  dkvhj         106 non-null    object
 14  WlYyy 5       92 non-null     object
 15  WlYyy 6       140 non-null    object
dtypes: float64(1), object(15)
memory usage: 32.2+ KB

In [9]:
# making a cop of the data to clean it
df = messy_df.copy()

In [10]:
# dropping the unnecessary columns
df.drop(['WlYyy', 'FmrIP href', 'dugSS src', 'cIVmB', 'iPqaD href 2', 'iPqaD href 3', 'dugSS src 2', 'WlYyy 3', 'iPqaD', 'iPqaD href 5', 'WlYyy 4', 'dkvhj', 'WlYyy 5', 'WlYyy 6'], axis=1 , inplace=True)

In [11]:
# renaming the columns
df.rename(columns={ 'bUshh':'Attraction Name', 'WlYyy 2':'Attraction Type'}, inplace=True)

In [12]:
# adding new columns
df['City'] = 'Marrakech'
df['Country'] = 'Morocco'

In [13]:
# check the total duplicated rows
sum(df.duplicated())

14

In [14]:
# drop the duplicated rows
df.drop_duplicates()

,Attraction Name,Attraction Type,City,Country
0,NaN,NaN,Marrakech,Morocco
1,Jardin Majorelle,Gardens,Marrakech,Morocco
2,Palácio da Bahia,Historic Sites • Architectural Buildings,Marrakech,Morocco
3,Anima André Heller Garden,Gardens,Marrakech,Morocco
4,Le Jardin Secret,Gardens,Marrakech,Morocco
...,...,...,...,...
251,Atlas Walkers,"Multi-day Tours • 4WD, ATV & Off-Road Tours",Marrakech,Morocco
252,Sahara Exploring Expedition Day Tours,"Multi-day Tours • 4WD, ATV & Off-Road Tours",Marrakech,Morocco
253,Morocco Private Excursion,Multi-day Tours • Taxis & Shuttles,Marrakech,Morocco
254,Marrakech Sweet Travel,City Tours • Multi-day Tours,Marrakech,Morocco
255,Marrakech Hidden Sites,Cultural Tours • Historical & Heritage Tours,Marrakech,Morocco

In [15]:
df.columns

Index(['Attraction Name', 'Attraction Type', 'City', 'Country'], dtype='object')

In [16]:
#checking for total null values
df.isnull().sum()

Attraction Name    11
Attraction Type     1
City                0
Country             0
dtype: int64

In [17]:
# reset the index
df.reset_index(drop=True)

,Attraction Name,Attraction Type,City,Country
0,NaN,NaN,Marrakech,Morocco
1,Jardin Majorelle,Gardens,Marrakech,Morocco
2,Palácio da Bahia,Historic Sites • Architectural Buildings,Marrakech,Morocco
3,Anima André Heller Garden,Gardens,Marrakech,Morocco
4,Le Jardin Secret,Gardens,Marrakech,Morocco
...,...,...,...,...
252,Sahara Exploring Expedition Day Tours,"Multi-day Tours • 4WD, ATV & Off-Road Tours",Marrakech,Morocco
253,Morocco Private Excursion,Multi-day Tours • Taxis & Shuttles,Marrakech,Morocco
254,Marrakech Sweet Travel,City Tours • Multi-day Tours,Marrakech,Morocco
255,Marrakech Hidden Sites,Cultural Tours • Historical & Heritage Tours,Marrakech,Morocco
256,NaN,1,Marrakech,Morocco

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Attraction Name  246 non-null    object
 1   Attraction Type  256 non-null    object
 2   City             257 non-null    object
 3   Country          257 non-null    object
dtypes: object(4)
memory usage: 8.2+ KB

In [19]:
# Store the clean dataset
df.to_csv('Marrakechclean.csv')